stages:
  - docker-build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  APP_NAME: test-react
  PORT_NUMBER : 80
  PORT : 8080
  
docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:latest
  script:
    - docker build --pull --rm -f -t "$TAG_LATEST" .

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

depyloy:
  stage: deploy
  script:
    - echo "Deploying to" $CI_REGISTRY_IMAGE
    - echo "$SERVER_USER"
    - echo "$SERVER_IP"
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p 28189 "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p 28189 "docker pull $TAG_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p 28189 "docker container rm -f $APP_NAME || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p 28189 "docker run -d -p $PORT:$PORT_NUMBER --name $APP_NAME $TAG_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p 28189 'docker rmi $(docker images -f "dangling=true" -q)'


